export { KpisDetailsComponent as KpisDetails } from "./kpis-details/kpis-details.component";
export { LocationMarkerComponent as LocationMarker} from "./location-marker/location-marker.component";
export { ImageViewComponent as  ImageView} from "./image-view/image-view.component";
export { ReportIssueComponent as ReportIssue } from "./report-issue/report-issue.component";
export { VehiclesOnMapComponent as VehiclesOnMap } from "./vehicles-on-map/vehicles-on-map.component";
export { VehicleReportComponent as VehicleReport } from "./vehicle-report/vehicle-report.component";
export { RouteMapperComponent as  RouteMapper} from "./route-mapper/route-mapper.component";
export { TripDetailsComponent as TripDetails} from "./trip-details/trip-details.component";
export { VehicleStatesComponent as VehicleStates} from "./vehicle-states/vehicle-states.component";
export { VehicleTripUpdateComponent as VehicleTripUpdate} from "./vehicle-trip-update/vehicle-trip-update.component";
export { ChangeVehicleStatusComponent as ChangeVehicleStatus } from "./change-vehicle-status/change-vehicle-status.component";
export { AddShortTargetComponent as AddShortTarget} from "./add-short-target/add-short-target.component";
export { PoliceStationComponent as PoliceStation} from "./police-station/police-station.component";
export { OdoMeterComponent as OdoMeter} from "./odo-meter/odo-meter.component";
export { EntityFlagsComponent as EntityFlags } from "./entity-flags/entity-flags.component";
export { VehicleOrdersComponent as VehicleOrders} from "./BidModals/vehicle-orders/vehicle-orders.component";
export { ChangeVehicleStatusByCustomerComponent as ChangeVehicleStatusByCustomer } from "./change-vehicle-status-by-customer/change-vehicle-status-by-customer.component";
